% from sources
standard_channels = { ...
	'satellites'								'count'; ...
	'time'										's'; ...
	'latitude'									'minutes'; ...
	'longitude'									'minutes'; ...
	'velocity'									'knots'; ...
	'velocity knots'							'knots'; ...
	'velocity kmh'								'kmh'; ...
	'heading'									''; ...
	'height'									''; ...
	'vertical velocity m/s'						'm/s'; ...
	'vertical velocity'							''; ...
	'velocity quality'							''; ...
	'long accel g'								''; ...
	'lat accel g'								''; ...
	'brake distance m'							'm'; ...
	'distance m'								'm'; ...
	'adc01-1'									''; ...
	'adc01-2'									''; ...
	'adc01-3'									''; ...
	'adc01-4'									''; ...
	'glonass_sats'								'count'; ...
	'gps_sats'									'count'; ...
	'yaw rate'									''; ...
	'latacc'									''; ...
	'reserved'									''; ...
	'yaw rate 2'								''; ...
	'latacc 2'									''; ...
	'solution type'								''; ...
	'velocity quality'							''; ...
	'internal temperature'						''; ...
	'cf_buffersize'								''; ...
	'ramaddress'								''; ...
	'event 1 time'								''; ...
	'event 2 time'								''; ...
	'battery 1 voltage'							''; ...
	'battery 2 voltage'							''; ...
% from tex's list
	'absolute heading'							''; ...
	'gps_longacc'								''; ...
	'gps_latacc'								''; ...
	'yaw rate deg/s'							''; ...
	'yaw_rate2'									''; ...
	'yaw_rate'									''; ...
	'yawrate'									''; ...
	'lateral accel (yaw sensor)'				''; ...
	'latacc_2'									''; ...
	'slip angle'								''; ...
	'slip_angle'								''; ...
	'radius of turn'							''; ...
	'trigger event time in clock counts'		''; ...
	'distance feet'								''; ...
	'gps distance from start point in metres'	''; ...
	'gps distance from start point in feet'		''; ...
	'incremental time in seconds'				''; ...
	'long acc calc'								''; ...
	'lat acc calc'								''; ...
	'x position in'								''; ...
	'y position in'								''; ...
	'relative height'							''; ...
	'relative height feet'						'ft'; ...
	'centre line deviation'						''; ...
};